<a href="https://colab.research.google.com/github/LAXMANPANT123/python-projects/blob/laxman/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [4]:
data = {'Name':['A','B','C'],'Age':[20,25,30],'City':['Delhi','Mumbai','Chennai']}
df = pd.DataFrame(data)

In [10]:
df.head()  # it shows the first five rows

  Name  Age     City
0    A   20    Delhi
1    B   25   Mumbai
2    C   30  Chennai

In [11]:
df.tail()  # it shows the last five rows

  Name  Age     City
0    A   20    Delhi
1    B   25   Mumbai
2    C   30  Chennai

In [13]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [14]:
df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [15]:
df.shape

(3, 3)

In [16]:
df.describe()

        Age
count   3.0
mean   25.0
std     5.0
min    20.0
25%    22.5
50%    25.0
75%    27.5
max    30.0

In [17]:
df['Name']

0    A
1    B
2    C
Name: Name, dtype: object

In [19]:
df.loc[0]  #select row by index

Name        A
Age        20
City    Delhi
Name: 0, dtype: object

In [20]:
df[df['Age'] > 22]

  Name  Age     City
1    B   25   Mumbai
2    C   30  Chennai

In [21]:
df['Salary'] = [30000, 40000, 50000]

In [23]:
df['Age'] = df['Age']+1

In [24]:
df.head()

  Name  Age     City  Salary
0    A   21    Delhi   30000
1    B   26   Mumbai   40000
2    C   31  Chennai   50000

In [25]:
df.drop('City', axis=1)

  Name  Age  Salary
0    A   21   30000
1    B   26   40000
2    C   31   50000

In [26]:
df.rename(columns={'Name': 'FullName'})

  FullName  Age     City  Salary
0        A   21    Delhi   30000
1        B   26   Mumbai   40000
2        C   31  Chennai   50000

In [27]:
df.sort_values('Age')

  Name  Age     City  Salary
0    A   21    Delhi   30000
1    B   26   Mumbai   40000
2    C   31  Chennai   50000

In [28]:
df.loc[2, "Age"] = 30

In [29]:
df.head()

  Name  Age     City  Salary
0    A   21    Delhi   30000
1    B   26   Mumbai   40000
2    C   30  Chennai   50000

In [31]:
df.fillna(0)   # fidm all nan value and replace them with 0

  Name  Age     City  Salary
0    A   21    Delhi   30000
1    B   26   Mumbai   40000
2    C   30  Chennai   50000

In [32]:
df['Age'].apply(lambda x:x*2)

0    42
1    52
2    60
Name: Age, dtype: int64

In [33]:
df['Age'].apply(lambda x: x + 5)

0    26
1    31
2    35
Name: Age, dtype: int64

In [34]:
df.groupby('City')['Salary'].mean()

City
Chennai    50000.0
Delhi      30000.0
Mumbai     40000.0
Name: Salary, dtype: float64

In [35]:
df['City'].value_counts()

City
Delhi      1
Mumbai     1
Chennai    1
Name: count, dtype: int64